---
php_memory_limit: "128M"
php_max_execution_time: "90"
php_upload_max_filesize: "256M"
php_packages:
  - php5
  - php5-cli
  - php5-common
  - php5-gd
  - php5-dev 
  - php5-mysql 
  - php5-curl
  - php-pear 
  - php5-imap 
  - php5-mcrypt 
  - php5-xmlrpc 
  - php5-xsl
